// <auto-generated />
namespace WisejWebApplication3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Default_Staff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Default_Staff));
        
        string IMigrationMetadata.Id
        {
            get { return "202411250859369_Default_Staff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
